version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      - DEBUG=0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gitnotify
      - REDIS_URL=redis://redis:6379/0
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      - db
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  celery_worker:
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: celery -A gitnotify worker -l info
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gitnotify
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - backend
      - redis
    networks:
      - app-network

  celery_beat:
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: celery -A gitnotify beat -l info
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gitnotify
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - backend
      - redis
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=gitnotify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:6-alpine
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
